# Quantitative Value Strategy

### Library Imports

In [64]:
import numpy as np
import pandas as pd
import requests
import xlsxwriter
from scipy import stats
import math

### Importing Our List of Stocks & API Token

In [65]:
from secrets import IEX_CLOUD_API_TOKEN
stocks = pd.read_csv('sp_500_stocks.csv')

### Making Our First API Call

In [66]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/quote?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()

### Parsing Our API Call

In [67]:
price = data['latestPrice']
pe_ratio = data['peRatio']
pe_ratio

37.43

### Executing A Batch API Call & Building Our DataFrame

In [68]:
# From StackoverFLow
def chunks(lst, n):
    """Yield Successive n-sized chunks from lst"""
    for i in range(0, len(lst), n):
        yield lst[i:i+n]
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))

my_columns = ['Ticker', 'Price', 'Price-to-Earnings Ratio', 'Number of Shares to Buy']

In [69]:
final_dataframe = pd.DataFrame(columns=my_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=quote&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        final_dataframe = final_dataframe.append(
            pd.Series(
                [
                    symbol,
                    data[symbol]['quote']['latestPrice'],
                    data[symbol]['quote']['peRatio'],
                    'n/a',
                ],
                index = my_columns
            ), ignore_index=True
        )
        
final_dataframe

    Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0        A  135.540                   57.98                     n/a
1      AAL   18.400                    -1.3                     n/a
2      AAP  157.060                   23.87                     n/a
3     AAPL  141.393                   37.24                     n/a
4     ABBV  106.720                   23.49                     n/a
..     ...      ...                     ...                     ...
500    YUM  110.310                   30.95                     n/a
501    ZBH  164.450                 -221.81                     n/a
502   ZBRA  488.670                   52.89                     n/a
503   ZION   52.930                    22.3                     n/a
504    ZTS  171.972                   50.35                     n/a

[505 rows x 4 columns]

### Removing Glamour Stocks

In [70]:
final_dataframe.sort_values('Price-to-Earnings Ratio', inplace=True)
final_dataframe = final_dataframe[final_dataframe['Price-to-Earnings Ratio'] > 0]
final_dataframe = final_dataframe[:50]
final_dataframe.reset_index(inplace=True)
final_dataframe.drop('index', axis=1, inplace=True)

In [71]:
final_dataframe

   Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0     NRG   41.480                    2.45                     n/a
1     AIV    4.949                    4.82                     n/a
2     UNM   26.686                    5.71                     n/a
3     BIO  664.395                    5.81                     n/a
4     ALL  104.477                     7.5                     n/a
5     AFL   48.980                    7.67                     n/a
6     CPB   48.020                    8.32                     n/a
7      CE  139.750                    8.34                     n/a
8    EBAY   65.610                    8.46                     n/a
9      KR   34.971                       9                     n/a
10    PHM   49.040                    9.19                     n/a
11    KIM   18.320                    9.22                     n/a
12    MET   57.870                    9.27                     n/a
13     BK   42.920                    9.77                     n/a
14    CTL   11.000                    9.97                     n/a
15    SRE  127.720                   10.02                     n/a
16    PGR   87.430                   10.04                     n/a
17    PNC  166.690                   10.31                     n/a
18    HII  184.890                   10.38                     n/a
19    NEE   84.500                    10.7                     n/a
20    HIG   50.502                    10.8                     n/a
21    DHI   83.280                   11.13                     n/a
22    CAH   52.450                   11.22                     n/a
23   BIIB  291.750                   11.37                     n/a
24    WHR  201.200                   11.87                     n/a
25    CVS   73.680                   11.99                     n/a
26    MAS   55.700                   12.01                     n/a
27    LEN   90.690                   12.02                     n/a
28    STT   75.890                    12.2                     n/a
29    HUM  389.600                   12.36                     n/a
30    TSN   66.950                   12.53                     n/a
31    MGM   36.100                   12.58                     n/a
32    PFG   56.770                   12.59                     n/a
33      C   67.740                   12.63                     n/a
34     VZ   55.500                    12.8                     n/a
35     GM   53.920                   12.81                     n/a
36   INTC   64.993                   12.85                     n/a
37   FOXA   33.450                   12.96                     n/a
38    UHS  130.430                   13.06                     n/a
39     MS   77.710                    13.1                     n/a
40   DISH   31.823                   13.51                     n/a
41   PBCT   15.844                   13.76                     n/a
42    LNC   54.530                   13.81                     n/a
43    ETR   95.810                   13.86                     n/a
44    HPQ   27.527                   13.98                     n/a
45    PNW   77.800                   14.04                     n/a
46    IBM  120.600                   14.09                     n/a
47    TRV  153.820                   14.15                     n/a
48    LMT  350.300                   14.36                     n/a
49    PPL   29.100                    14.4                     n/a

### Calculating the Number of Shares to Buy

In [72]:
def portfolio_input():
    global portfolio_size
    
    portfolio_size = input("How big is your portfolio")
    
    try:
        val = float(portfolio_size)
    except ValueError:
        print("That's not a number. Try again")
        portfolio_size = input("Enter the value of your portfolio")

In [73]:
portfolio_input()

How big is your portfolio1000000000000

In [74]:
position_size = float(portfolio_size) / len(final_dataframe.index)
for row in final_dataframe.index:
    final_dataframe.loc[row, 'Number of Shares to Buy'] = math.floor(position_size / final_dataframe.loc[row, 'Price'])

### Building a Better (and More Realistic) Value Strategy

In [75]:
symbol = 'AAPL'
batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol}&types=quote,advanced-stats&token={IEX_CLOUD_API_TOKEN}'
data = requests.get(batch_api_call_url).json()

# Price-to-earnings ratio
pe_ratio = data[symbol]['quote']['peRatio']

# Price to Book ratio
pb_ratio = data[symbol]['advanced-stats']['priceToBook']

# price-to-sales ratio
ps_ratio = data[symbol]['advanced-stats']['priceToSales']

# Enterprise Value divided by earnings before interest, taxes, depreciation and amortization (EV/EBITDA)
enterprise_value = data[symbol]['advanced-stats']['enterpriseValuee']
ebitda = data[symbol]['advanced-stats']['EBITDA']
ev_to_ebitda = enterprise_value / ebitda

# Enterprise Vlaue divided by Gross Profit (EV/GP)
gross_profit = data[symbol]['advanced-stats']['grossProfit']
ev_to_gross_profit = enterprise_value / gross_profit

KeyError: 'enterpriseValuee'

In [ ]:
rv_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy', 
    'Price-to-Earnings Ratio',
    'PE Percentile',
    'Price-to-Book Ratio',
    'PB Percentile',
    'Price-to-Sales Ratio',
    'PS Percentile',
    'EV/EBITDA',
    'EV/EBITDA Percentile',
    'EV/GP',
    'EV/GP Percentile',
    'RV Score'
]

rv_dataframe = pd.DataFrame(columns = rv_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=quote,advanced-stats&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        enterprise_value = data[symbol]['advanced-stats']['enterpriseValue']
        ebitda = data[symbol]['advanced-stats']['EBITDA']
        gross_profit = data[symbol]['advanced-stats']['grossProfit']
        
        try:
            ev_to_ebitda = enterprise_value/ebitda
        except TypeError:
            ev_to_ebitda = np.NaN
        
        try:
            ev_to_gross_profit = enterprise_value/gross_profit
        except TypeError:
            ev_to_gross_profit = np.NaN
            
        rv_dataframe = rv_dataframe.append(
            pd.Series([
                symbol,
                data[symbol]['quote']['latestPrice'],
                'N/A',
                data[symbol]['quote']['peRatio'],
                'N/A',
                data[symbol]['advanced-stats']['priceToBook'],
                'N/A',
                data[symbol]['advanced-stats']['priceToSales'],
                'N/A',
                ev_to_ebitda,
                'N/A',
                ev_to_gross_profit,
                'N/A',
                'N/A'
        ],
        index = rv_columns),
            ignore_index = True
        )

In [ ]:
rv_dataframe

### Dealing With Missing Data in Our DataFrame

In [ ]:
rv_dataframe[rv_dataframe.isnull().any(axis=1)]

In [ ]:
for column in ['Price-to-Earnings Ratio', 'Price-to-Book Ratio','Price-to-Sales Ratio',  'EV/EBITDA','EV/GP']:
    rv_dataframe[column].fillna(rv_dataframe[column].mean(), inplace = True)

### Calculating Value Percentiles

In [ ]:
metrics = {
            'Price-to-Earnings Ratio': 'PE Percentile',
            'Price-to-Book Ratio':'PB Percentile',
            'Price-to-Sales Ratio': 'PS Percentile',
            'EV/EBITDA':'EV/EBITDA Percentile',
            'EV/GP':'EV/GP Percentile'
}

metrics['Price-to-Earnings Ratio']

for metric in metrics.keys():
    for row in rv_dataframe.index:
        rv_dataframe.loc[row, metrics[metric]] = stats.percentileofscore(rv_dataframe[metric], rv_dataframe.loc[row, metric])

### Calculating the RV Score

In [ ]:
from statistics import mean

for row in rv_dataframe.index:
    value_percentiles = []
    for metric in metrics.keys():
        value_percentiles.append(rv_dataframe.loc[row, metrics[metric]])
    rv_dataframe.loc[row, 'RV Score'] = mean(value_percentiles)

### Selecting the 50 Best Value Stocks

In [ ]:
rv_dataframe.sort_values('RV Score', ascending=True, inplace=True)
rv_dataframe = rv_dataframe[:50]
rv_dataframe.reset_index(drop=True, inplace=True)

### Calculating the Number of Shares to Buy

In [ ]:
portfolio_input()

In [ ]:
position_size = float(portfolio_size) / len(rv_dataframe.index)
for row in rv_dataframe.index:
    rv_dataframe.loc[row, 'Number of Shares to Buy'] = position_size/rv_dataframe.loc[row, 'Price']

### Formatting Our Excel Output

In [ ]:
writer = pd.ExcelWriter('value_strategy.xlsx', engine='xlsxwriter')
rv_dataframe.to_excel(writer, sheet_name='Value Strategy', index = False)

In [ ]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

float_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

### Creating the Formats We'll Need For Our .xlsx File

In [ ]:
column_formats = {
                    'A': ['Ticker', string_template],
                    'B': ['Price', dollar_template],
                    'C': ['Number of Shares to Buy', integer_template],
                    'D': ['Price-to-Earnings Ratio', float_template],
                    'E': ['PE Percentile', percent_template],
                    'F': ['Price-to-Book Ratio', float_template],
                    'G': ['PB Percentile',percent_template],
                    'H': ['Price-to-Sales Ratio', float_template],
                    'I': ['PS Percentile', percent_template],
                    'J': ['EV/EBITDA', float_template],
                    'K': ['EV/EBITDA Percentile', percent_template],
                    'L': ['EV/GP', float_template],
                    'M': ['EV/GP Percentile', percent_template],
                    'N': ['RV Score', percent_template]
                 }

for column in column_formats.keys():
    writer.sheets['Value Strategy'].set_column(f'{column}:{column}', 25, column_formats[column][1])
    writer.sheets['Value Strategy'].write(f'{column}1', column_formats[column][0], column_formats[column][1])

### Saving Our Excel Output

In [ ]:
writer.save()